name: Cartier Watch Stock Check

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 toml

      - name: Create config.toml
        run: |
          cat <<EOF > config.toml
          target_url = "https://www.cartier.com/ko-kr/watches/all-collections/tank/%ED%83%B1%ED%81%AC-%EB%A8%B8%EC%8A%A4%ED%8A%B8-%EB%93%9C-%EA%B9%8C%EB%A5%B4%EB%9D%BC%EC%9D%B8%EC%97%90-%EC%9B%8C%EC%B9%98-CRWSTA0107.html"
          watching_text = "상담원 연결"
          expected_text = "구매 가능"
          telegram_bot_token = "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          telegram_chat_id = "${{ secrets.TELEGRAM_CHAT_ID }}"
          EOF

      - name: Run scraper
        run: python check_item.py
